export const EXAM_START_REQUEST = "EXAM_START_REQUEST";
export const EXAM_NO_MORE_APPROACHES = "EXAM_NO_MORE_APPROACHES";
export const EXAM_STARTED = "EXAM_STARTED";
export const EXAM_END_REQUEST = "EXAM_END_REQUEST";
export const EXAM_ENDED = "EXAM_ENDED";